### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by 3Ricool** [QData/AttentiveChrome#1]
Hi,

when I downloaded data from REMC I found out that there are E001-H3K4me1, E002-H3K4me1 and so on. So which one should I choose?

Eric

**Comment by qiyanjun** [comment]
We have provided a toy dataset to test out model in the data subdirectory of v2PyTorch

The complete set of 56 Cell Type datasets is located at https://zenodo.org/record/2652278

The rows are bins for all genes (100 rows per gene) and the columns are organised as follows:

GeneID, Bin ID, H3K27me3 count, H3K36me3 count, H3K4me1 count, H3K4me3 count, H3K9me3 counts, Binary Label for gene expression (0/1)
e.g. 000003,1,4,3,0,8,4,1

**Comment by Sajad-Ul-Mulk** [comment]
thanks @qiyanjun  for providing this data...

**Comment by Sajad-Ul-Mulk** [comment]
Ma'am can we use this data for DeepDiff as well...???

**Comment by jacklanchantin** [comment]
@SUM113 the DeepDiff data is provided in the DeepDiff Github repository: https://github.com/QData/DeepDiffChrome

**Comment by Sajad-Ul-Mulk** [comment]
@jacklanchantin thanks bro.... very much...

**Comment by Sajad-Ul-Mulk** [comment]
hi...sir can u tell me why is E005 and E006 train test valid file empty while expression file has values in it......thanks in advance..
