### ISSUE TITLE
Dataset split problem

### ISSUE THREAD

**Issue by 3Ricoo** [QData/AttentiveChrome#2]
Here I had two questions about your Datasets:
1. why you divide data into three equal parts(train/test/validation) in advance?  
2. What is the data set divided according to?
When I ran the toy dataset, the AUC score is extremely low, which led me to think if there is a problem with the data division.

**Comment by jacklanchantin** [comment]
Hi, did you try to download the real datasets from https://zenodo.org/record/2652278 ? The toy dataset is just to verify that the code is running ok.

**Comment by 3Ricoo** [comment]
Yeah, I did. The real processed datasets are also following the trisection. I had run all of them, unfortunately, the results are not stable. 
Best validation avgAUC of E003:0.49618797939848824
Best test avgAUC of E003:0.43220490020846014

Best validation avgAUC of E004:0.7705088302164319
Best test avgAUC of E004:0.8030481043469708

Best validation avgAUC of E003:0.49618797939848824
Best test avgAUC of E003:0.43220490020846014

Best validation avgAUC of E004:0.7705088302164319
Best test avgAUC of E004:0.8030481043469708

Best validation avgAUC of E005:0.7731582141119595
Best test avgAUC of E005:0.8081235159803248

Best validation avgAUC of E006:0.7668800150439201
Best test avgAUC of E006:0.819764557166778

Best validation avgAUC of E007:0.5293938813296111
Best test avgAUC of E007:0.4601162798836268

Best validation avgAUC of E011:0.43655870977570715
Best test avgAUC of E011:0.3924943285265782

Best validation avgAUC of E012:0.5349610187799219
Best test avgAUC of E012:0.4706689081641777

Best validation avgAUC of E013:0.587481388080323
Best test avgAUC of E013:0.5695791310259983

……

**Comment by jacklanchantin** [comment]
There was an issue with the training code. I have pushed 2 line changes. Can you try to pull them and see if that works?

**Comment by 3Ricoo** [comment]
Thanks. The algorithm gets more stable.

**Comment by jacklanchantin** [comment]
Great - thanks for opening this up. I'll close it now.
